# Use peacock/sky as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: sky-playlists-mongo
    volumes:
      - sky-playlists-mongo-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: peacock
      MONGO_INITDB_ROOT_PASSWORD: sky
      
  mongo-express:
    image: mongo-express
    container_name: sky-playlists-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: peacock
      ME_CONFIG_MONGODB_ADMINPASSWORD: sky
      ME_CONFIG_MONGODB_URL: mongodb://peacock:sky@mongo:27017/
      

volumes:
  sky-playlists-mongo-data:
    driver: local